name: logr
description: A minimal logging API for dart
version: 0.1.5+2
homepage: https://github.com/v42one/dartx/tree/main/packages/logr

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  contextdart: ^1.2.1

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.20.2
  analyzer: ^4.1.0