name: logr
description: A minimal logging API for dart
version: 0.1.2
homepage: https://github.com/v42one/dartx/tree/main/packages/logr

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  contextdart: ^1.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.1
  analyzer: ^3.1.0
