name: dartx
repository: https://github.com/v42one/dartx

packages:
  - packages/**

command:
  version:
    branch: main
    linkToCommits: true
    workspaceChangelog: false

ide:
  intellij: true

scripts:
  analyze:
    run: melos exec -c 1 -- "dart analyze . --fatal-infos"
    select-package:
      ignore:
        - "*monorepo*"

  test:
    run: melos exec -c 1 -- "dart test"
    select-package:
      dir-exists:
        - "test/"

  format: dart format -o write .

  dep: melos exec "flutter pub upgrade"

  generate:
    run: melos run generate:dart && melos run generate:flutter

  generate:dart:
    run: melos exec -c 1 --depends-on="build_runner" --no-flutter -- "dart run build_runner build --delete-conflicting-outputs"

  generate:flutter:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
