name: pubtidy
description: generate flatten entry file of package
version: 0.0.3+1
homepage: https://github.com/v42one/dartx/tree/main/packages/pubtidy

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  path: "^1.8.1"
  analyzer: "^3.4.0"

dev_dependencies:
  test: ^1.20.1

executables:
  pubtidy: