name: roundtripper
description: another composable, Future-based library for making HTTP requests
version: 0.4.0
homepage: https://github.com/v42one/dartx/tree/main/packages/roundtripper

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  logr: ^0.1.5+2
  http_parser: ^4.0.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  dio: ^4.0.4
  contextdart: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^2.0.1
  filesize: ^2.0.1
  test: ^1.20.2
  analyzer: ^4.1.0
  source_gen: ^1.2.1
  freezed: ^2.0.3+1