name: roundtripper
description: another composable, Future-based library for making HTTP requests
version: 0.3.3
homepage: https://github.com/v42one/dartx/tree/main/packages/roundtripper

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  logr: ^0.1.2
  http_parser: ^4.0.0
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  dio: ^4.0.4
  contextdart: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.4
  filesize: ^2.0.1
  test: ^1.20.1
  analyzer: ^3.4.0
  source_gen: ^1.2.1
  freezed: ^1.1.1
