name: contextdart
description: pure golang context.Context implements in dart
version: 1.2.0
homepage: https://github.com/v42one/dartx/tree/main/packages/contextdart


environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.2
  analyzer: ^3.4.0