name: contextdart
description: pure golang context.Context implements in dart
version: 1.2.1
homepage: https://github.com/v42one/dartx/tree/main/packages/contextdart


environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.20.2
  analyzer: ^4.1.0