name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.4
        with:
          sdk: stable

      - run: make bootstrap test

      - if: github.event_name != 'pull_request'
        name: publish pub credentials
        env:
          PUB_HOSTED_URL: https://pub.dev
        run: |
          mkdir -p "${XDG_CONFIG_HOME}/dart"
          echo '${{ secrets.PUB_CREDENTIALS_JSON }}' > "${XDG_CONFIG_HOME}/dart/pub-credentials.json"
          melos clean
          melos publish --no-dry-run --yes
