name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - run: make bootstrap
      - run: make lint
      - run: make test

#  publish:
#    needs: test
#    if: github.event_name != 'pull_request'
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: k-paxian/dart-package-publisher@v1.3
#        with:
#          credentialJson: ${{ secrets.PUB_CREDENTIALS_JSON }}
#          skipTests: true
